# Generated by Django 6.0.5 on 2026-05-25 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The legal name of the organization.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for routing.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawIngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Procurement/Fuel CSV Export'), ('UTILITY_ELECTRICITY', 'Utility Electricity CSV Export'), ('TRAVEL_API', 'Corporate Travel JSON/API')], help_text='The format/source from which the data originates.', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Currently Processing'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed Processing')], default='PENDING', help_text='Current ingestion state.', max_length=20)),
                ('error_summary', models.TextField(blank=True, help_text='High-level processing errors or stack trace details if failed.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Execution metadata (e.g. filename, file size, line counts).')),
                ('organization', models.ForeignKey(help_text='The tenant organization associated with this record.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='carbon_app.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User context responsible for initiating the ingestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(help_text='Original JSON representation of the imported row before translation.')),
                ('row_index', models.PositiveIntegerField(help_text='Line/index number of this record inside the raw payload.')),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Successfully Processed'), ('ERROR', 'Processing Error')], default='UNPROCESSED', help_text='Processing status of this individual row.', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Trace log details if processing of this row failed.', null=True)),
                ('organization', models.ForeignKey(help_text='The tenant organization associated with this record.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='carbon_app.organization')),
                ('job', models.ForeignKey(help_text='The ingestion job that imported this raw data.', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='carbon_app.rawingestionjob')),
            ],
            options={
                'ordering': ['job', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(help_text='Target primary key of the EmissionActivityRecord (persisted after deletion).')),
                ('action', models.CharField(choices=[('CREATE', 'Emission Record Created'), ('UPDATE', 'Emission Record Updated'), ('DELETE', 'Emission Record Deleted'), ('APPROVE', 'Emission Record Signed Off / Approved'), ('FLAG', 'Emission Record Flagged for Anomaly')], help_text='The action category executed on the record.', max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="State changes tracking structure: {'field': [old_value, new_value]}.")),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='The timestamp when this transaction occurred.')),
                ('changed_by', models.ForeignKey(blank=True, help_text='The application user who triggered this change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Tenant context under which the change happened.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='carbon_app.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'record_id'], name='carbon_app__organiz_7acbe5_idx'), models.Index(fields=['organization', '-timestamp'], name='carbon_app__organiz_b1dcb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmissionActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Indirect Emissions (Electricity/Purchased Energy)'), ('SCOPE_3', 'Scope 3 - Value Chain / Other Indirect')], help_text='Scope categorization of the activity.', max_length=10)),
                ('category', models.CharField(help_text='Activity category (e.g. Purchased Electricity, Business Flights, Diesel Procurement).', max_length=100)),
                ('original_quantity', models.DecimalField(decimal_places=6, help_text='Parsed amount directly from raw upload.', max_digits=19)),
                ('original_unit', models.CharField(help_text='Source measurement unit (e.g. Gallons, kWh, passenger-km).', max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, help_text='Amount normalized to the standard unit of measurement.', max_digits=19)),
                ('normalized_unit', models.CharField(help_text='Standardized system reporting unit (e.g. kg CO2e, kWh).', max_length=50)),
                ('transaction_date', models.DateField(help_text='Date of physical activity occurrence.')),
                ('plant_facility_code', models.CharField(help_text='Identifier for the local plant, facility, or branch office.', max_length=100)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged (Anomaly Detected)'), ('APPROVED', 'Approved')], default='PENDING', help_text='Current state of review for audit signoff.', max_length=20)),
                ('anomaly_flag_reason', models.TextField(blank=True, help_text='Reason why this row was flagged as an anomaly.', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of validation signoff.', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Auditor who reviewed and signed off on this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The tenant organization associated with this record.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='carbon_app.organization')),
                ('raw_row', models.OneToOneField(blank=True, help_text='Reference to the immutable raw data row for auditing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_record', to='carbon_app.rawdatarow')),
            ],
            options={
                'ordering': ['-transaction_date', 'id'],
                'indexes': [models.Index(fields=['organization', '-transaction_date'], name='carbon_app__organiz_b0c54a_idx'), models.Index(fields=['organization', 'review_status'], name='carbon_app__organiz_269744_idx'), models.Index(fields=['organization', 'plant_facility_code', '-transaction_date'], name='carbon_app__organiz_b4b7f7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rawingestionjob',
            index=models.Index(fields=['organization', '-created_at'], name='carbon_app__organiz_1d165a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestionjob',
            index=models.Index(fields=['status'], name='carbon_app__status_ec5929_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatarow',
            index=models.Index(fields=['organization', 'status'], name='carbon_app__organiz_9a43a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawdatarow',
            unique_together={('job', 'row_index')},
        ),
    ]
