# Generated by Django 6.0.5 on 2026-05-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawingestionjob',
            name='source_type',
            field=models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Procurement/Fuel CSV Export'), ('UTILITY_ELECTRICITY', 'Utility Electricity CSV Export'), ('TRAVEL_API', 'Corporate Travel JSON/API'), ('DOCUMENT_OCR', 'Universal AI/OCR Document Ingestion')], help_text='The format/source from which the data originates.', max_length=50),
        ),
    ]
